# vim: set expandtab shiftwidth=2 tabstop=8:
version: 2
jobs:
  build:
    working_directory: ~/tuhi
    docker:
      - image: fedora:latest
    steps:
      - run:
          command: |
            dnf install -y meson gettext python3-devel pygobject3-devel python3-flake8 desktop-file-utils libappstream-glib python3-pytest python3-pyxdg python3-pyyaml
      - checkout
      - run:
          command: |
            meson builddir
            ninja -C builddir test
      - store_artifacts:
          path: ~/tuhi/builddir/meson-logs
  flatpak:
    docker:
      - image: fedora:latest
    steps:
      - run:
          command: |
            dnf install -y flatpak-builder
      - checkout:
      - run:
          command: |
            flatpak-builder -v --user --force-clean _flatpak_build org.freedesktop.Tuhi.json

workflows:
  version: 2
  compile_and_test:
    jobs:
      - build
      - flatpak
